### ISSUE TITLE
تمپلیت

### ISSUE THREAD

**Issue by mjmaher987** [AmooHashem/flutter_parse#1]
سلام.
یه سوالی، تمپلیت اماده ای هست که یه اپ رو بیاریم سریع بالا؟
برای پروژه یکی از درسا نیازه

**Comment by AmooHashem** [comment]
سلام
نمی‌دونم، میشه از همین پروژه استفاده کنی. یه سرچ ریزی هم که کردم، اینجا انگار یه تمپلیت آماده وجود داره:

https://github.com/webfactorymk/flutter-template

**Comment by mjmaher987** [comment]
هااا
خیلی ممنون
